os: linux
dist: bionic
language: python
python:
  - "3.7"

git:
  submodules: false

env:
  global:
    - MAKEFLAGS="-j2"

jobs:
  include:
    - stage: "Tests"
      name: "Python PEP8 checks"
      install:
        - pip install -r conf/requirements.txt
      script:
        - "make format"
        - "test $(git status --porcelain | wc -l) -eq 0 || { git diff; false; }"

    - stage: "Run"
      name: iverilog
      install:
        - ./.github/travis/install.sh
      script:
        - ./.github/travis/run.sh

    - stage: "Run"
      name: moore
      install:
        - ./.github/travis/install.sh
      script:
        - ./.github/travis/run.sh

    - stage: "Run"
      name: odin_ii
      install:
        - ./.github/travis/install.sh
      script:
        - ./.github/travis/run.sh

    - stage: "Run"
      name: slang
      install:
        - ./.github/travis/install.sh
      script:
        - ./.github/travis/run.sh

    - stage: "Run"
      name: sv-parser
      install:
        - ./.github/travis/install.sh
      script:
        - ./.github/travis/run.sh

    - stage: "Run"
      name: tree-sitter-verilog
      install:
        - ./.github/travis/install.sh
      script:
        - ./.github/travis/run.sh

    - stage: "Run"
      name: yosys
      install:
        - ./.github/travis/install.sh
      script:
        - ./.github/travis/run.sh

    - stage: "Run"
      name: verible
      install:
        - ./.github/travis/install.sh
      script:
        - ./.github/travis/run.sh

    - stage: "Run"
      name: verilator
      install:
        - ./.github/travis/install.sh
      script:
        - ./.github/travis/run.sh

    - stage: "Run"
      name: zachjs-sv2v
      install:
        - ./.github/travis/install.sh
      script:
        - ./.github/travis/run.sh
