# Copyright (C) 2019-2021  The SymbiFlow Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier: ISC


name: sv-test-env
channels:
  - LiteX-Hub
#  - pkgw-forge
#  - conda-forge
dependencies:
#  - LiteX-Hub::iverilog
#  - LiteX-Hub::moore
#  - LiteX-Hub::odin_ii
#  - LiteX-Hub::slang
#  - LiteX-Hub::surelog
#  - LiteX-Hub::sv-parser
#  - LiteX-Hub::tree-sitter-verilog
#  - LiteX-Hub::yosys-uhdm
#  - LiteX-Hub::verible
#  - LiteX-Hub::verilator
#  - gxx_impl_linux-64
#  - LiteX-Hub::yosys
#  - LiteX-Hub::antmicro-yosys-complete
#  - LiteX-Hub::zachjs-sv2v
  - ccache
  - python=3.8
  - pip
  - pip:                            # Packages installed from PyPI
    - -r requirements.txt
