name: sv-test-env
channels:
  - symbiflow
  - pkgw-forge
  - conda-forge
dependencies:
#  - iverilog
#  - moore
#  - odin_ii
#  - slang
#  - surelog
#  - sv-parser
#  - tree-sitter-verilog
#  - verible
#  - verilator
#  - yosys
#  - zachjs-sv2v
  - ccache
  - python=3.7
  - pip
  - pip:                            # Packages installed from PyPI
    - -r file:requirements.txt
