name: trigger-lint
on:
  pull_request:

jobs:
  upload_event_file:
    runs-on: [self-hosted, Linux, X64, gcp-custom-runners]
    container: ubuntu:jammy-20221130
    steps:
      - uses: actions/checkout@v2
      - name: Copy event file
        run: cp "$GITHUB_EVENT_PATH" ./event.json
      - name: Upload event file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: event.json
          path: event.json
